apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost-found-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lost-found-app
  template:
    metadata:
      labels:
        app: lost-found-app
    spec:
      containers:
      - name: lost-found-app
        image: ghcr.io/mohan454522/lost-found-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "sqlite:///lost_found.db"
        - name: SECRET_KEY
          value: "production-secret-key-2024"
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: lost-found-service
spec:
  selector:
    app: lost-found-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer